
#ifndef _XDLDOC_H
#define _XDLDOC_H

#include "attr/docattr.h"
#include "attr/cssattr.h"
#include "attr/xmlattr.h"
#include "attr/svgattr.h"

#include "doc/domdoc.h"
#include "doc/xmldoc.h"
#include "doc/funcdoc.h"
#include "doc/metadoc.h"
#include "doc/schemadoc.h"
#include "doc/wsdldoc.h"
#include "doc/soapdoc.h"
#include "doc/jsondoc.h"
#include "doc/imagesdoc.h"
#include "doc/notesdoc.h"
#include "doc/memodoc.h"
#include "doc/richdoc.h"
#include "doc/tagdoc.h"
#include "doc/svgdoc.h"
#include "doc/annodoc.h"
#include "doc/tooldoc.h"
#include "doc/titledoc.h"
#include "doc/griddoc.h"
#include "doc/properdoc.h"
#include "doc/listdoc.h"
#include "doc/labeldoc.h"
#include "doc/treedoc.h"
#include "doc/menudoc.h"
#include "doc/statisdoc.h"
#include "doc/formdoc.h"
#include "doc/splitdoc.h"
#include "doc/topogdoc.h"
#include "doc/statusdoc.h"
#include "doc/dialogdoc.h"
#include "doc/diagramdoc.h"
#include "doc/archdoc.h"
#include "doc/calendardoc.h"
#include "doc/taskdoc.h"
#include "doc/plotdoc.h"
#include "doc/eventdoc.h"


#endif //XDLDOC_H
